torchrun --standalone --nproc_per_node 1 run_pretrain.py \
    --model_config configs/llama_1b.json \
    --lr 3e-4 \
    --batch_size 8 \
    --total_batch_size 256 \
    --max_length 1024 \
    --num_billion_training_tokens 13.1 \
    --warmup_steps 2000 \
    --weight_decay 0.1 \
    --dtype float32 \
    --eval_every 2000 \
    --save_every 5000 \
    --single_gpu \
    --optimizer q_adam_mini_8bit \
    --project '1B' \
    --weight_group_size 256 \
    --stochastic_round \
    --stochastic_round_state \
    --name new1_1B_3e-4_256_nowq > new1_1B_3e-4_256_nowq